[project]
name = "petrarl"
authors = ["Hannes Buechi <hannes.buechi@gmail.com>", "Hanno Hiss <hannohiss@me.com>"]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[dependencies]
python = "3.11"
pandas = "2.2.2"
numpy = "1.26.0"
pymongo = "4.10.1"
seaborn = "0.12.2"
matplotlib = "3.8.4"
schedule = "1.2.2"
cvxpy = "1.5.2"
openpyxl = "3.1.5"
pyodbc = "5.1.0"
python-dotenv = "1.0.1"
pytz = "2024.1"
scikit-learn = "1.4.0"
requests = "2.26.0"
uvicorn = "0.29.0"
fastapi = "0.111.0"
ipykernel = "6.29.5"
pytorch = "2.6.0"
stable-baselines3 = ">=2.5.0,<3"
gymnasium = ">=1.0.0,<2"
gymnasium-all = ">=1.0.0,<2"
sb3-contrib = ">=2.3.0,<3"
ipywidgets = ">=8.1.5,<9"
protobuf = ">=5.28.3,<6"
tensorflow = ">=2.18.0,<3"
libgfortran = ">=5.0.0,<16"
orjson = ">=3.10.18,<4"

[pypi-dependencies]
ortools = "==9.10.4067"
rl4co = "==0.5.2"
vrplib = "*"

[target.osx-64.dependencies]
pytorchrl = ">=0.6.0"
tensordict = "==0.7.2"

[target.osx-arm64.pypi-dependencies]
pytorchrl = ">=0.6.0"
tensordict = "==0.7.2"
